title: Mano Sriram
logo: /assets/img/logo.png
description: 
show_downloads: true
theme: jekyll-theme-minimal
resume: /resume.pdf
favicon: /assets/img/favicon.svg
host: "https://manosriram.com"
baseurl: ""
